[build]
  base    = "shadcn-landing-page-main"
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Headers para otimização de performance e segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirecionamentos para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirecionamento para HTTPS
[[redirects]]
  from = "http://actplanconsultoria.com/*"
  to = "https://actplanconsultoria.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.actplanconsultoria.com/*"
  to = "https://actplanconsultoria.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.actplanconsultoria.com/*"
  to = "https://actplanconsultoria.com/:splat"
  status = 301
  force = true
